---
- name: ansible playbook for installing nginx and vim
  hosts: all
  become: true
  tasks:
    - name: installing nginx and vim for remote servers and updating the repo.
      # module used
      package:
        # package name
              name:
                      # these are variables which will be defined in inventory file.
                      - "{{ nginx_package }}"
                      - "{{ vim_package }}"
              state: latest
              update_cache: yes

