---
- name: ansible playbook for installing nginx and vim
  hosts: all
  become: true
  tasks:
    - name: installing nginx and vim for debian based Operating System and updating the repository
      # module used
      apt:
        # package name
              name:
                      - nginx
                      - vim
              state: latest
              update_cache: yes
      # condition : checking the distribution of the OS
      when: ansible_distribution=="Debian"

    - name: installing nginx and vim for CentOS and updating the repository
      # module used
      dnf:
        # package name
              name: 
                      - nginx
                      - vim-enhanced
              state: latest
              update_cache: yes
      # condition
      when: ansible_distribution=="CentOS"

